### ISSUE TITLE
Peer Review on Awesome Book ES-6

### ISSUE THREAD

**Issue by benardop** [yasinabdmahmood/Awesome-books#2]
@yasinabdmahmood very good work done so far in this project 👍 
I just have one suggestion to make:
-  In the 'add button' shadow, you may please try and adjust the opacity of the background shadow to make more aligned with the
   background-color

**Comment by maaloum** [comment]
Great job but I suggest that you give the footer a position absolute so it can stick always at the bottom of the page

**Comment by yasinabdmahmood** [comment]
fixed all the mentioned problem in the github issue
